# Generated by Django 3.1.4 on 2021-11-19 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='leave_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='leave',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='take_over',
        ),
        migrations.AddField(
            model_name='leave',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
