# Generated by Django 3.1.4 on 2021-12-16 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave', '0002_auto_20211119_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='leave',
            name='kind',
            field=models.CharField(blank=True, choices=[('Annual', 'Annual leave'), ('Half', 'Half day leave'), ('Holiday', 'Holiday')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='take_over',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
