# Generated by Django 3.1.4 on 2021-12-30 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_auto_20211216_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='leave',
            name='kind',
            field=models.CharField(blank=True, choices=[('Annual', '연차'), ('morning_Half', '반차 (오전)'), ('afternoon_Half', '반차 (오후)'), ('Holiday', '휴가')], max_length=20, null=True),
        ),
    ]
