# Generated by Django 3.1.4 on 2022-01-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20211230_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='kind',
            field=models.CharField(blank=True, choices=[('Annual', '연차'), ('Monthly', '월차'), ('morning_Half', '반차 (오전)'), ('afternoon_Half', '반차 (오후)')], max_length=20, null=True),
        ),
    ]
