# Generated by Django 3.1.4 on 2022-01-13 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_auto_20220106_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='take_over',
        ),
    ]
