# Generated by Django 3.1.4 on 2022-02-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_remove_leave_take_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='kind',
            field=models.CharField(blank=True, choices=[('Annual', '연차'), ('Monthly', '월차'), ('morning_Half', '반차 (오전)'), ('afternoon_Half', '반차 (오후)'), ('official', '공가 및 특별휴가')], max_length=20, null=True),
        ),
    ]
