# Generated by Django 3.1.4 on 2024-01-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_auto_20220217_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='kind',
            field=models.CharField(blank=True, choices=[('Annual', '연차'), ('Monthly', '월차'), ('morning_Half', '반차 (오전)'), ('afternoon_Half', '반차 (오후)'), ('official', '공가 및 특별휴가'), ('carry_over', '이월 (1일)'), ('carry_over_Half', '이월 (0.5일)')], max_length=20, null=True),
        ),
    ]
