# Generated by Django 3.1.2 on 2021-01-05 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('screening', 'Screening'), ('ongoing', 'On going'), ('off', 'Off'), ('screening_fail', 'Screening fail')], max_length=30, null=True)),
                ('no', models.CharField(max_length=50, null=True)),
                ('register_number', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('dx', models.CharField(choices=[('stomach_cancer', 'Stomach cancer'), ('sarcoma', 'Sarcoma'), ('colorectal_cancer', 'Colorectal cancer'), ('bladder_cancer', 'Bladder cancer'), ('rcc', 'RCC'), ('prostate_cancer', 'Prostate cancer'), ('lung_cancer', 'Lung cancer'), ('breast_cancer', 'Breast cancer'), ('hcc', 'HCC'), ('gb', 'GB'), ('pancreatic_cancer', 'Pancreatic cancer'), ('head_neck_cancer', 'Head/Neck cancer'), ('melanoma', 'Melanoma'), ('ovarian_cancer', 'Ovarian cancer'), ('cervix_cancer', 'Cervix cancer'), ('solid_cancer', 'Solid cancer'), ('other', '기타(other)')], max_length=100, null=True)),
                ('previous_tx', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('crc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle', models.CharField(blank=True, max_length=30, null=True)),
                ('dosing_date', models.DateField(null=True)),
                ('tx_dose', models.TextField(blank=True, null=True)),
                ('photo_date', models.DateField(max_length=30, null=True)),
                ('response', models.CharField(blank=True, choices=[('CR', 'CR'), ('PR', 'PR'), ('SD', 'SD'), ('PD', 'PD'), ('ND', 'ND')], max_length=30, null=True)),
                ('response_text', models.CharField(blank=True, max_length=30, null=True)),
                ('toxicity', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.assignment')),
            ],
        ),
    ]
