# Generated by Django 3.1.2 on 2021-01-05 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.research'),
        ),
    ]
