# Generated by Django 3.1.4 on 2021-03-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_assignment_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('screening', 'Screening'), ('screening_fail', 'Screening fail'), ('ongoing', 'On going'), ('off', 'Off'), ('FU', 'FU')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='cycle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='dosing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='photo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.CharField(blank=True, choices=[('', ''), ('CR', 'CR'), ('PR', 'PR'), ('SD', 'SD'), ('PD', 'PD'), ('ND', 'ND')], default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
