# Generated by Django 3.1.2 on 2021-01-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_assignment_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='response_text',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
