# Generated by Django 3.1.2 on 2021-01-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20210105_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='cycle',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.CharField(blank=True, choices=[('CR', 'CR'), ('PR', 'PR'), ('SD', 'SD'), ('PD', 'PD'), ('ND', 'ND')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tx_dose',
            field=models.TextField(blank=True, default=''),
        ),
    ]
