# Generated by Django 3.1.4 on 2021-03-30 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20210324_1111'),
        ('feedback', '0003_auto_20210105_1123'),
    ]

    operations = [
    ]
