# Generated by Django 3.1.4 on 2021-03-30 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0004_merge_20210330_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='PI',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='crc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dx',
            field=models.CharField(blank=True, choices=[('stomach_cancer', 'Stomach cancer'), ('sarcoma', 'Sarcoma'), ('colorectal_cancer', 'Colorectal cancer'), ('bladder_cancer', 'Bladder cancer'), ('rcc', 'RCC'), ('prostate_cancer', 'Prostate cancer'), ('lung_cancer', 'Lung cancer'), ('breast_cancer', 'Breast cancer'), ('hcc', 'HCC'), ('gb', 'GB'), ('pancreatic_cancer', 'Pancreatic cancer'), ('head_neck_cancer', 'Head/Neck cancer'), ('melanoma', 'Melanoma'), ('ovarian_cancer', 'Ovarian cancer'), ('cervix_cancer', 'Cervix cancer'), ('solid_cancer', 'Solid cancer'), ('other', '기타(other)')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='register_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(blank=True, choices=[('screening', 'Screening'), ('screening_fail', 'Screening fail'), ('ongoing', 'On going'), ('off', 'Off'), ('FU', 'FU')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='cycle',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.CharField(blank=True, choices=[('', ''), ('CR', 'CR'), ('PR', 'PR'), ('SD', 'SD'), ('PD', 'PD'), ('ND', 'ND')], max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response_text',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
