# Generated by Django 3.1.2 on 2021-01-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_auto_20210106_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='cycle',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.CharField(blank=True, choices=[('CR', 'CR'), ('PR', 'PR'), ('SD', 'SD'), ('PD', 'PD'), ('ND', 'ND')], max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response_text',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tx_dose',
            field=models.TextField(blank=True),
        ),
    ]
