# Generated by Django 3.1.4 on 2021-03-31 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20210330_1446'),
        ('feedback', '0007_auto_20210106_1152'),
    ]

    operations = [
    ]
