# Generated by Django 3.1.4 on 2021-03-31 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_merge_20210331_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='day',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='cycle',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response',
            field=models.CharField(blank=True, choices=[('', ''), ('CR', 'CR'), ('PR', 'PR'), ('SD', 'SD'), ('PD', 'PD'), ('ND', 'ND')], default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='response_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='toxicity',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='tx_dose',
            field=models.TextField(blank=True, default=''),
        ),
    ]
