# Generated by Django 3.1.4 on 2021-04-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_auto_20210331_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ICF_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
