# Generated by Django 3.1.4 on 2021-04-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0011_auto_20210419_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='PI',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
