# Generated by Django 3.1.4 on 2021-05-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_auto_20210430_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='scr_fail',
            field=models.DateField(blank=True, null=True),
        ),
    ]
