# Generated by Django 3.1.4 on 2021-06-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0015_feedback_scr_fail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='dx',
            field=models.CharField(blank=True, choices=[('stomach_cancer', 'Stomach cancer'), ('small_bowel_cancer', 'small bowel cancer'), ('colorectal_cancer', 'Colorectal cancer'), ('NSCLC', 'NSCLC'), ('SCLC', 'SCLC'), ('head_neck_cancer', 'Head/Neck cancer'), ('esophageal', 'esophageal'), ('hcc', 'HCC'), ('gb', 'GB'), ('BT', 'BT'), ('pancreatic_cancer', 'Pancreatic cancer'), ('breast_cancer', 'Breast cancer'), ('ovarian_cancer', 'Ovarian cancer'), ('endometrial_cancer', 'Endometrial cancer'), ('vaginal_cancer', 'Vaginal cancer'), ('cervix_cancer', 'Cervix cancer'), ('vulva_cancer', 'Vulva cancer'), ('rcc', 'RCC'), ('ureter_cancer', 'Ureter cancer'), ('bladder_cancer', 'Bladder cancer'), ('prostate_cancer', 'Prostate cancer'), ('solid_cancer', 'Solid cancer'), ('melanoma', 'Melanoma'), ('sarcoma', 'Sarcoma'), ('other', '기타(other)')], max_length=500, null=True),
        ),
    ]
