# Generated by Django 3.1.4 on 2021-06-14 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_auto_20210608_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='curr_crc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
