# Generated by Django 3.1.4 on 2021-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0017_assignment_curr_crc'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='phase',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
