# Generated by Django 3.1.4 on 2021-08-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0018_assignment_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='next_visit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
