# Generated by Django 3.1.4 on 2021-08-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0019_feedback_next_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(blank=True, choices=[('screening', 'Screening'), ('screening_fail', 'Screening fail'), ('ongoing', 'On going'), ('off', 'Off'), ('FU', 'FU'), ('pre-screening', 'Pre-screening'), ('pre-screening-fail', 'Pre-screening fail')], max_length=30, null=True),
        ),
    ]
