# Generated by Django 3.1.4 on 2022-06-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_contact_user'),
        ('feedback', '0021_feedback_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='curr_crc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.contact'),
        ),
    ]
