# Generated by Django 3.1.4 on 2022-06-17 08:26

from django.db import migrations, models
import django.db.models.deletion
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0022_auto_20220615_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRECIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=800)),
                ('file', models.FileField(upload_to=feedback.models.user_directory_path)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.assignment')),
            ],
        ),
    ]
