# Generated by Django 3.1.4 on 2022-09-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0024_auto_20220914_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_accompany',
            field=models.CharField(choices=[('1', 'Y'), ('0', 'N')], default='0', max_length=50, null=True),
        ),
    ]
