# Generated by Django 3.1.4 on 2023-01-04 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0025_feedback_is_accompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ECOG',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
