# Generated by Django 3.1.4 on 2021-12-03 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0020_supporting_technician'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[], max_length=120, null=True)),
            ],
            options={
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Inform', 'Inform'), ('BioClinica', 'BioClinica'), ('PPD', 'PPD'), ('Almac(call)', 'Almac(call)'), ('TrialManager', 'TrialManager')], max_length=50, null=True)),
                ('information', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('vendor_id', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor_pw', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Research_Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('cro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='miscellaneous.cro')),
                ('research', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.research')),
                ('vendor', models.ManyToManyField(to='miscellaneous.Vendor')),
            ],
        ),
    ]
