# Generated by Django 3.1.4 on 2022-01-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0002_auto_20211231_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporting',
            name='kinds',
            field=models.CharField(blank=True, choices=[('PK', 'PK'), ('EKG', 'EKG'), ('PK/EKG', 'PK/EKG'), ('Bx', 'Bx'), ('LAB', 'LAB')], max_length=50, null=True),
        ),
    ]
