# Generated by Django 3.1.4 on 2022-02-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0003_auto_20220104_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporting',
            name='pre_hour',
        ),
        migrations.AlterField(
            model_name='supporting',
            name='kinds',
            field=models.CharField(blank=True, choices=[('PK-pre', 'PK-pre'), ('PK-post', 'PK-post'), ('EKG', 'EKG'), ('PK/EKG', 'PK/EKG'), ('Bx', 'Bx'), ('LAB', 'LAB')], max_length=50, null=True),
        ),
    ]
