# Generated by Django 3.1.4 on 2022-03-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0005_supporting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporting',
            name='supporting_type',
            field=models.ManyToManyField(to='miscellaneous.Supporting_type'),
        ),
    ]
