# Generated by Django 3.1.4 on 2022-03-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0006_supporting_supporting_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporting',
            name='supporting_type',
        ),
        migrations.AddField(
            model_name='supporting',
            name='supporting_type',
            field=models.CharField(blank=True, choices=[('진검 검체', '진검 검체'), ('별도 채혈', '별도 채혈'), ('채혈실 동행', '채혈실 동행'), ('분주', '분주')], max_length=50, null=True),
        ),
    ]
