# Generated by Django 3.1.4 on 2022-03-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0007_auto_20220322_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporting',
            name='supporting_type',
            field=models.CharField(blank=True, choices=[('진검검체', '진검 검체'), ('별도채혈', '별도 채혈'), ('채혈실동행', '채혈실 동행'), ('분주', '분주')], max_length=50, null=True),
        ),
    ]
