# Generated by Django 3.1.4 on 2022-03-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0008_auto_20220322_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporting',
            name='supporting_type',
            field=models.CharField(blank=True, choices=[('진검검체', '진검검체'), ('별도채혈', '별도채혈'), ('채혈실동행', '채혈실동행'), ('분주', '분주')], max_length=50, null=True),
        ),
    ]
