# Generated by Django 3.1.4 on 2022-03-24 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0021_feedback_uploader'),
        ('miscellaneous', '0009_auto_20220322_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('crc', models.CharField(blank=True, max_length=50, null=True)),
                ('scheduled_time', models.CharField(blank=True, choices=[('오전', '오전'), ('오후', '오후'), ('기타', '기타')], max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('checking', models.CharField(blank=True, max_length=1, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.assignment')),
            ],
        ),
    ]
