# Generated by Django 3.1.4 on 2022-04-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miscellaneous', '0010_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporting',
            name='kinds',
            field=models.CharField(blank=True, choices=[('PK-pre', 'PK-pre'), ('PK-post', 'PK-post'), ('EKG', 'EKG'), ('PK/EKG', 'PK/EKG'), ('Bx', 'Bx'), ('LAB', 'LAB'), ('PK+LAB', 'PK+LAB')], max_length=50, null=True),
        ),
    ]
