# Generated by Django 3.1.4 on 2022-11-15 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_contact_user'),
        ('research', '0036_auto_20221020_1738'),
        ('miscellaneous', '0011_auto_20220408_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='QC_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[], max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='information',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='link',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='research',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_id',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_pw',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='value',
            field=models.CharField(choices=[], max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='QC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QC_count', models.IntegerField(null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('QC_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miscellaneous.qc_category')),
                ('crc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.contact')),
                ('research', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='research.research')),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='miscellaneous.vendor')),
            ],
        ),
    ]
