# Generated by Django 3.1.2 on 2021-01-05 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(default='', max_length=50)),
                ('m_scr', models.CharField(default='', max_length=50)),
                ('m_ongo', models.CharField(default='', max_length=50)),
                ('m_enroll', models.CharField(default='', max_length=50)),
                ('m_target', models.CharField(default='', max_length=50)),
                ('m_waiting', models.CharField(blank=True, default='', max_length=50)),
                ('cancer', models.CharField(choices=[('Stomach', 'Stomach cancer'), ('Sarcoma', 'Sarcoma'), ('CRC', 'Colorectal cancer'), ('Urological', 'Urological cancer'), ('Lung', 'Lung cancer'), ('Melanoma', 'Melanoma')], default='', max_length=50)),
                ('slide_number', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancer', models.CharField(choices=[('Stomach', 'Stomach cancer'), ('Sarcoma', 'Sarcoma'), ('CRC', 'Colorectal cancer'), ('Urological', 'Urological cancer'), ('Lung', 'Lung cancer'), ('Melanoma', 'Melanoma')], default='', max_length=50)),
                ('slide_number', models.IntegerField(default='1')),
                ('slide', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='protocol_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol_file_ko', models.FileField(blank=True, null=True, upload_to='protocol_ko/')),
                ('protocol_file_eng', models.FileField(blank=True, null=True, upload_to='protocol_eng/')),
                ('inclusion', models.ImageField(blank=True, null=True, upload_to='criteria/inclusion/')),
                ('exclusion', models.ImageField(blank=True, null=True, upload_to='criteria/exclusion/')),
                ('clinical_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataroom.image')),
            ],
        ),
        migrations.CreateModel(
            name='Image_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_top', models.IntegerField(blank=True, null=True)),
                ('link_left', models.IntegerField(blank=True, null=True)),
                ('link_right', models.IntegerField(blank=True, null=True)),
                ('link_bottom', models.IntegerField(blank=True, null=True)),
                ('clinical_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataroom.image')),
            ],
        ),
    ]
