# Generated by Django 3.1.2 on 2021-01-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_waitinglist'),
        ('dataroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='research',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='research.research'),
        ),
        migrations.AlterField(
            model_name='image',
            name='cancer',
            field=models.CharField(choices=[('Stomach', 'Stomach cancer'), ('Sarcoma', 'Sarcoma'), ('CRC', 'Colorectal cancer'), ('Urological', 'Urological cancer'), ('Lung', 'Lung cancer'), ('Melanoma', 'Melanoma'), ('Phase1', 'Phase1')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='cancer',
            field=models.CharField(choices=[('Stomach', 'Stomach cancer'), ('Sarcoma', 'Sarcoma'), ('CRC', 'Colorectal cancer'), ('Urological', 'Urological cancer'), ('Lung', 'Lung cancer'), ('Melanoma', 'Melanoma'), ('Phase1', 'Phase1')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='protocol_upload',
            name='clinical_trial',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='research.research'),
        ),
    ]
