# Generated by Django 3.1.4 on 2021-01-26 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_waitinglist'),
        ('dataroom', '0002_auto_20210120_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='research.research'),
        ),
    ]
