# Generated by Django 3.1.4 on 2021-02-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0004_auto_20210223_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cancer',
            field=models.CharField(choices=[('Stomach', 'Stomach cancer'), ('Sarcoma', 'Sarcoma'), ('CRC', 'Colorectal cancer'), ('Urological', 'Urological cancer'), ('Lung', 'Lung cancer'), ('Melanoma', 'Melanoma'), ('Solid(GC)', 'Solid(GC)'), ('Solid(Urological)', 'Solid(Urological)'), ('Phase1', 'Phase1')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='cancer',
            field=models.CharField(choices=[('Stomach', 'Stomach cancer'), ('Sarcoma', 'Sarcoma'), ('CRC', 'Colorectal cancer'), ('Urological', 'Urological cancer'), ('Lung', 'Lung cancer'), ('Melanoma', 'Melanoma'), ('Solid(GC)', 'Solid(GC)'), ('Solid(Urological)', 'Solid(Urological)'), ('Phase1', 'Phase1')], default='', max_length=50),
        ),
    ]
