# Generated by Django 3.1.4 on 2021-04-14 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0009_auto_20210407_1520'),
        ('dataroom', '0005_auto_20210223_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cancer',
            field=models.CharField(choices=[('Stomach', 'Stomach cancer'), ('Sarcoma', 'Sarcoma'), ('CRC', 'Colorectal cancer'), ('Urological', 'Urological cancer'), ('Lung', 'Lung cancer'), ('Melanoma', 'Melanoma'), ('Solid(GC)', 'Solid(GC)'), ('Solid(Urological)', 'Solid(Urological)'), ('Phase1', 'Phase1'), ('Pancreatic', 'Pancreatic cancer')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='image_link',
            name='clinical_trial',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataroom.image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='cancer',
            field=models.CharField(choices=[('Stomach', 'Stomach cancer'), ('Sarcoma', 'Sarcoma'), ('CRC', 'Colorectal cancer'), ('Urological', 'Urological cancer'), ('Lung', 'Lung cancer'), ('Melanoma', 'Melanoma'), ('Solid(GC)', 'Solid(GC)'), ('Solid(Urological)', 'Solid(Urological)'), ('Phase1', 'Phase1'), ('Pancreatic', 'Pancreatic cancer')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='protocol_upload',
            name='clinical_trial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.research'),
        ),
        migrations.CreateModel(
            name='Notepad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notepad', models.TextField(blank=True, default='')),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('research', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.research')),
            ],
        ),
    ]
