# Generated by Django 3.1.4 on 2022-01-21 05:22

import dataroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0006_auto_20210414_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol_upload',
            name='reference',
            field=models.ImageField(blank=True, null=True, storage=dataroom.models.OverwriteStorage(), upload_to='reference'),
        ),
    ]
