# Generated by Django 3.1.4 on 2022-01-27 07:50

import dataroom.models
import dataroom.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0007_protocol_upload_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocol_upload',
            name='reference',
            field=models.ImageField(blank=True, null=True, storage=dataroom.models.OverwriteStorage(), upload_to=dataroom.utils.rename_imagefile_to_uuid),
        ),
        migrations.DeleteModel(
            name='Notepad',
        ),
    ]
