# Generated by Django 3.1.4 on 2022-04-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0012_auto_20220419_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('Training', 'Training'), ('15A', '15A 병동'), ('CTC', 'CTC'), ('병리과', '병리과'), ('심전도_폐기능', '심전도, 폐기능'), ('안과', '안과'), ('암병원_채혈실', '암병원 채혈실'), ('영상의학과', '영상의학과'), ('종양내과_외래', '종양내과 외래'), ('초음파', '초음파'), ('항암주사실', '항암주사실'), ('온도기록지', '온도기록지(-70도 냉동고)'), ('A팀관리기기', 'A팀 관리기기')], default='', max_length=50),
        ),
    ]
