# Generated by Django 3.1.4 on 2023-10-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0014_auto_20230817_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cancer',
            field=models.CharField(choices=[('Breast', 'Breast'), ('Stomach', 'Stomach'), ('Sarcoma', 'Sarcoma'), ('CRC', 'CRC'), ('Urological', 'Urological'), ('Lung', 'Lung'), ('Melanoma', 'Melanoma'), ('Solid(GC)', 'Solid(GC)'), ('Solid(Urological)', 'Solid(Urological)'), ('Phase1', 'Phase1'), ('Pancreatic', 'Pancreatic')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='cancer',
            field=models.CharField(choices=[('Breast', 'Breast'), ('Stomach', 'Stomach'), ('Sarcoma', 'Sarcoma'), ('CRC', 'CRC'), ('Urological', 'Urological'), ('Lung', 'Lung'), ('Melanoma', 'Melanoma'), ('Solid(GC)', 'Solid(GC)'), ('Solid(Urological)', 'Solid(Urological)'), ('Phase1', 'Phase1'), ('Pancreatic', 'Pancreatic')], default='', max_length=50),
        ),
    ]
