# Generated by Django 3.1.4 on 2023-10-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0015_auto_20231006_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_link',
            name='link_bottom',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='image_link',
            name='link_left',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='image_link',
            name='link_right',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='image_link',
            name='link_top',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
