# Generated by Django 3.1.4 on 2023-10-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0016_auto_20231011_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='m_waiting',
        ),
    ]
