# Generated by Django 3.1.4 on 2023-10-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0017_remove_image_m_waiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='cancer',
            field=models.CharField(choices=[('Breast', 'Breast'), ('Stomach', 'Stomach'), ('Sarcoma', 'Sarcoma'), ('CRC', 'CRC'), ('Urological', 'Urological'), ('Lung', 'Lung'), ('Melanoma', 'Melanoma'), ('Phase1', 'Phase1'), ('Pancreatic', 'Pancreatic')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='page',
            name='cancer',
            field=models.CharField(choices=[('Breast', 'Breast'), ('Stomach', 'Stomach'), ('Sarcoma', 'Sarcoma'), ('CRC', 'CRC'), ('Urological', 'Urological'), ('Lung', 'Lung'), ('Melanoma', 'Melanoma'), ('Phase1', 'Phase1'), ('Pancreatic', 'Pancreatic')], default='', max_length=50),
        ),
    ]
