# Generated by Django 3.1.4 on 2024-07-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0019_gcpmaterial_gcpmaterialcategory_gcpmaterialdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='asset_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
