# Generated by Django 3.1.4 on 2024-07-26 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0020_auto_20240726_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='version',
        ),
    ]
