# Generated by Django 3.1.4 on 2024-09-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataroom', '0021_remove_material_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='asset_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
