# Generated by Django 3.1.2 on 2021-01-05 01:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import research.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[], max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Biopsy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[], max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Brain_METS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[], max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[], max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chemotherapy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[], max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IO_Naive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[], max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[], max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[], max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PDL1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[], max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[], max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_recruiting', models.BooleanField(default=True)),
                ('research_name', models.CharField(max_length=2000, null=True)),
                ('crc', models.CharField(max_length=2000, null=True)),
                ('PI', models.CharField(max_length=2000, null=True)),
                ('contact', models.CharField(max_length=2000, null=True)),
                ('medicine_name', models.CharField(max_length=2000, null=True)),
                ('turn_around_time', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('liver_function', models.TextField(blank=True, null=True)),
                ('lung_function', models.TextField(blank=True, null=True)),
                ('heart_function', models.TextField(blank=True, null=True)),
                ('kidney_function', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('alternation', models.ManyToManyField(to='research.Alternation')),
                ('biopsy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.biopsy')),
                ('brain_mets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.brain_mets')),
                ('cancer', models.ManyToManyField(to='research.Cancer')),
                ('chemotherapy', models.ManyToManyField(to='research.Chemotherapy')),
                ('io_naive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.io_naive')),
                ('lesion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.lesion')),
                ('line', models.ManyToManyField(to='research.Line')),
                ('pdl1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.pdl1')),
                ('phase', models.ManyToManyField(to='research.Phase')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=800)),
                ('file', models.FileField(upload_to=research.models.user_directory_path)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.research')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_type', models.CharField(choices=[('create_research', '연구 생성'), ('edit_research', '연구 수정'), ('remove_research', '연구 삭제'), ('assign_patient', '환자 배정'), ('remove_patient', '환자 삭제')], max_length=150)),
                ('summary', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedback.feedback')),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.research')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
