# Generated by Django 3.1.4 on 2021-01-18 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('doctor', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1)),
                ('age', models.IntegerField()),
                ('curr_status', models.TextField(blank=True, max_length=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cancer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.cancer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
