# Generated by Django 3.1.4 on 2021-02-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_waitinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waitinglist',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='curr_status',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='doctor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='sex',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True),
        ),
    ]
