# Generated by Django 3.1.4 on 2021-02-08 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20210203_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitinglist',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
