# Generated by Django 3.1.4 on 2021-03-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20210208_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='research_explanation',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
