# Generated by Django 3.1.4 on 2021-03-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_research_research_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='is_recruiting',
            field=models.CharField(choices=[('Recruiting', 'Recruiting'), ('Not Recruiting', 'Not Recruiting'), ('Holding', 'Holding')], max_length=50, null=True),
        ),
    ]
