# Generated by Django 3.1.4 on 2021-04-05 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_auto_20210318_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='ONCO_CR_COUNT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_scr', models.CharField(blank=True, max_length=50)),
                ('r_ongo', models.CharField(blank=True, max_length=50)),
                ('r_enroll', models.CharField(blank=True, max_length=50)),
                ('r_target', models.CharField(blank=True, max_length=50)),
                ('r_waiting', models.CharField(blank=True, max_length=50)),
                ('cancer', models.CharField(blank=True, choices=[('Stomach', 'Stomach cancer'), ('Sarcoma', 'Sarcoma'), ('CRC', 'Colorectal cancer'), ('Urological', 'Urological cancer'), ('Lung', 'Lung cancer'), ('Melanoma', 'Melanoma'), ('Solid(GC)', 'Solid(GC)'), ('Solid(Urological)', 'Solid(Urological)'), ('Phase1', 'Phase1')], max_length=50)),
                ('research', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='research.research')),
            ],
        ),
    ]
