# Generated by Django 3.1.4 on 2021-04-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_onco_cr_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='onco_cr_count',
            name='r_FU',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onco_cr_count',
            name='r_scr_fail',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
