# Generated by Django 3.1.4 on 2021-04-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0008_auto_20210405_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onco_cr_count',
            name='cancer',
            field=models.CharField(blank=True, choices=[('Stomach', 'Stomach cancer'), ('Sarcoma', 'Sarcoma'), ('CRC', 'Colorectal cancer'), ('Urological', 'Urological cancer'), ('Lung', 'Lung cancer'), ('Melanoma', 'Melanoma'), ('Solid', 'Solid'), ('Solid(GC)', 'Solid(GC)'), ('Solid(Urological)', 'Solid(Urological)'), ('Phase1', 'Phase1')], max_length=50),
        ),
    ]
