# Generated by Django 3.1.4 on 2021-05-20 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0010_auto_20210518_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglist',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.phase'),
        ),
        migrations.AlterField(
            model_name='waitinglist',
            name='cancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.cancer'),
        ),
        migrations.CreateModel(
            name='research_WaitingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('doctor', models.CharField(max_length=10, null=True)),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F')], max_length=1, null=True)),
                ('age', models.IntegerField(null=True)),
                ('curr_status', models.TextField(max_length=500, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.research')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
