# Generated by Django 3.1.4 on 2021-05-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_auto_20210520_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='team',
            field=models.CharField(choices=[('CLUE', 'CLUE'), ('GSI', 'GSI'), ('etc', 'etc')], max_length=50, null=True),
        ),
    ]
