# Generated by Django 3.1.4 on 2021-06-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_research_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='is_recruiting',
            field=models.CharField(choices=[('Recruiting', 'Recruiting'), ('Not yet recruiting', 'Not yet recruiting'), ('Completed', 'Completed'), ('Holding', 'Holding')], max_length=50, null=True),
        ),
    ]
