# Generated by Django 3.1.4 on 2021-06-25 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0013_auto_20210607_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_Initiation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_research_name', models.CharField(blank=True, max_length=100)),
                ('PI', models.CharField(blank=True, max_length=100)),
                ('crc', models.CharField(blank=True, max_length=100)),
                ('initiation_date', models.CharField(blank=True, max_length=200)),
                ('memo', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
