# Generated by Django 3.1.4 on 2021-06-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_pre_initiation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='medicine_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
