# Generated by Django 3.1.4 on 2021-07-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0015_auto_20210625_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_initiation',
            name='team',
            field=models.CharField(choices=[('CLUE', 'CLUE'), ('GSI', 'GSI'), ('etc', 'etc')], max_length=50, null=True),
        ),
    ]
