# Generated by Django 3.1.4 on 2021-08-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0016_pre_initiation_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onco_cr_count',
            name='cancer',
        ),
        migrations.AddField(
            model_name='onco_cr_count',
            name='cancer',
            field=models.ManyToManyField(to='research.Cancer'),
        ),
    ]
