# Generated by Django 3.1.4 on 2021-08-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0017_auto_20210809_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_initiation',
            name='initiation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
