# Generated by Django 3.1.4 on 2021-09-10 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0020_auto_20210812_1633'),
        ('research', '0018_auto_20210813_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_date', models.DateField(blank=True, null=True)),
                ('pre_lab_date', models.CharField(blank=True, max_length=50, null=True)),
                ('kinds', models.CharField(blank=True, choices=[('PK', 'PK'), ('EKG', 'EKG'), ('Bx', 'Bx'), ('LAB', 'LAB')], max_length=50, null=True)),
                ('pre_hour', models.CharField(blank=True, max_length=2, null=True)),
                ('post_hour', models.CharField(blank=True, max_length=2, null=True)),
                ('crc', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.assignment')),
            ],
        ),
    ]
