# Generated by Django 3.1.4 on 2021-09-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0019_supporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporting',
            name='technician',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
