# Generated by Django 3.1.2 on 2021-12-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0020_supporting_technician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporting',
            name='pre_lab_date',
        ),
        migrations.AlterField(
            model_name='supporting',
            name='lab_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
