# Generated by Django 3.1.4 on 2021-12-31 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0021_auto_20211213_1727'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Supporting',
        ),
    ]
