# Generated by Django 3.1.4 on 2022-01-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0022_delete_supporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_initiation',
            name='set_up',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
