# Generated by Django 3.1.4 on 2022-01-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0023_pre_initiation_set_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='onco_A',
            field=models.BooleanField(default=True),
        ),
    ]
