# Generated by Django 3.1.4 on 2022-01-12 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_contact_team'),
        ('research', '0024_research_onco_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='first_backup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_backup', to='user.contact'),
        ),
        migrations.AddField(
            model_name='research',
            name='second_backup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_backup', to='user.contact'),
        ),
    ]
