# Generated by Django 3.1.4 on 2022-01-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0025_auto_20220112_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='type',
            field=models.CharField(choices=[('IIT', 'IIT'), ('SIT', 'SIT'), ('EAP', 'EAP'), ('PMS', 'PMS'), ('완화 연구', '완화 연구'), ('etc', 'etc')], max_length=50, null=True),
        ),
    ]
