# Generated by Django 3.1.4 on 2022-03-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_contact_eng_name'),
        ('research', '0026_research_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='crc',
        ),
        migrations.AddField(
            model_name='research',
            name='crc',
            field=models.ManyToManyField(related_name='crc', to='user.Contact'),
        ),
    ]
