# Generated by Django 3.1.4 on 2022-03-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0027_auto_20220311_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='study_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
