# Generated by Django 3.1.4 on 2022-04-20 08:28

from django.db import migrations, models
import django.db.models.deletion
import research.models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0028_research_study_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='End_research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_name', models.CharField(max_length=500, null=True)),
                ('study_code', models.CharField(max_length=500, null=True)),
                ('PI', models.CharField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('종료보고완료', '종료 보고 완료'), ('결과보고완료', '결과 보고 완료'), ('장기보관예정', '장기 보관 예정'), ('장기보관완료', '장기 보관 완료')], max_length=50, null=True)),
                ('binder_location', models.CharField(max_length=500, null=True)),
                ('storage_date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='research',
            name='binder_location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='status',
            field=models.CharField(choices=[('종료보고완료', '종료 보고 완료'), ('결과보고완료', '결과 보고 완료'), ('장기보관예정', '장기 보관 예정'), ('장기보관완료', '장기 보관 완료')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='storage_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('imagename', models.CharField(max_length=800)),
                ('image', models.ImageField(upload_to=research.models.research_binder_image_directory_path)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.research')),
            ],
        ),
        migrations.CreateModel(
            name='End_UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('imagename', models.CharField(max_length=800)),
                ('image', models.ImageField(upload_to=research.models.end_research_binder_image_directory_path)),
                ('end_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.end_research')),
            ],
        ),
    ]
