# Generated by Django 3.1.4 on 2022-05-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0029_auto_20220420_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='is_pre_screening',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
