# Generated by Django 3.1.4 on 2022-05-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_contact_user'),
        ('research', '0030_auto_20220518_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_initiation',
            name='type',
            field=models.CharField(choices=[('IIT', 'IIT'), ('SIT', 'SIT'), ('EAP', 'EAP'), ('PMS', 'PMS'), ('완화 연구', '완화 연구'), ('etc', 'etc')], max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='pre_initiation',
            name='set_up',
        ),
        migrations.AddField(
            model_name='pre_initiation',
            name='set_up',
            field=models.ManyToManyField(to='user.Contact'),
        ),
    ]
