# Generated by Django 3.1.4 on 2022-06-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0031_auto_20220527_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pre_initiation',
            name='type',
            field=models.CharField(choices=[('IIT', 'IIT'), ('SIT', 'SIT'), ('EAP', 'EAP'), ('PMS', 'PMS'), ('완화 연구', '완화 연구'), ('etc', 'etc'), ('IIT(기타/EAP)', 'IIT(기타/EAP)')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='type',
            field=models.CharField(choices=[('IIT', 'IIT'), ('SIT', 'SIT'), ('EAP', 'EAP'), ('PMS', 'PMS'), ('완화 연구', '완화 연구'), ('etc', 'etc'), ('IIT(기타/EAP)', 'IIT(기타/EAP)')], max_length=50, null=True),
        ),
    ]
