# Generated by Django 3.1.4 on 2022-07-29 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0032_auto_20220616_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onco_cr_count',
            name='r_FU',
        ),
        migrations.RemoveField(
            model_name='onco_cr_count',
            name='r_enroll',
        ),
        migrations.RemoveField(
            model_name='onco_cr_count',
            name='r_ongo',
        ),
        migrations.RemoveField(
            model_name='onco_cr_count',
            name='r_scr',
        ),
        migrations.RemoveField(
            model_name='onco_cr_count',
            name='r_scr_fail',
        ),
        migrations.RemoveField(
            model_name='onco_cr_count',
            name='r_waiting',
        ),
    ]
