# Generated by Django 3.1.4 on 2022-10-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0033_auto_20220729_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='CTC_contract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
