# Generated by Django 3.1.4 on 2022-10-18 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0034_research_ctc_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='CTC_contract',
        ),
    ]
