# Generated by Django 3.1.4 on 2022-10-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0035_remove_research_ctc_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_initiation',
            name='CTC_contract',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pre_initiation',
            name='CTC_non_contract_reason',
            field=models.TextField(blank=True),
        ),
    ]
