# Generated by Django 3.1.4 on 2022-12-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0036_auto_20221020_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='end_research',
            name='status',
            field=models.CharField(choices=[('종료보고완료', '종료 보고 완료'), ('결과보고완료', '결과 보고 완료'), ('장기보관완료', '장기 보관 완료')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='status',
            field=models.CharField(choices=[('종료보고완료', '종료 보고 완료'), ('결과보고완료', '결과 보고 완료'), ('장기보관완료', '장기 보관 완료')], max_length=50, null=True),
        ),
    ]
