# Generated by Django 3.1.4 on 2022-12-30 07:49

from django.db import migrations, models
import django.db.models.deletion
import research.models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0037_auto_20221227_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='end_research',
            name='CRA',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='end_research',
            name='end_brief',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='end_research',
            name='result_brief',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='CRA',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='end_brief',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='result_brief',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Research_Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=800)),
                ('file', models.FileField(upload_to=research.models.research_archive_directory_path)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.research')),
            ],
        ),
        migrations.CreateModel(
            name='End_Research_Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=800)),
                ('file', models.FileField(upload_to=research.models.end_research_archive_directory_path)),
                ('end_research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.end_research')),
            ],
        ),
    ]
