# Generated by Django 3.1.4 on 2023-01-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0038_auto_20221230_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[], max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
