# Generated by Django 3.1.4 on 2023-01-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0039_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='type',
        ),
        migrations.AddField(
            model_name='research',
            name='type',
            field=models.ManyToManyField(to='research.Type'),
        ),
    ]
