# Generated by Django 3.1.4 on 2023-02-16 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0041_crms_etc_irb_mfds_multicenter_preperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_initiation',
            name='CRO',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pre_initiation',
            name='alternation',
            field=models.ManyToManyField(to='research.Alternation'),
        ),
        migrations.AddField(
            model_name='pre_initiation',
            name='cancer',
            field=models.ManyToManyField(to='research.Cancer'),
        ),
        migrations.AddField(
            model_name='pre_initiation',
            name='chemotherapy',
            field=models.ManyToManyField(to='research.Chemotherapy'),
        ),
        migrations.AddField(
            model_name='pre_initiation',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pre_initiation',
            name='is_commence',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pre_initiation',
            name='is_withhold',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pre_initiation',
            name='phase',
            field=models.ManyToManyField(to='research.Phase'),
        ),
        migrations.AddField(
            model_name='pre_initiation',
            name='study_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pre_initiation',
            name='study_explanation',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.RemoveField(
            model_name='pre_initiation',
            name='type',
        ),
        migrations.AddField(
            model_name='pre_initiation',
            name='type',
            field=models.ManyToManyField(to='research.Type'),
        ),
        migrations.CreateModel(
            name='Pre_Initiation_SIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feasibility', models.DateField(blank=True, null=True)),
                ('PSV', models.DateTimeField(blank=True, null=True)),
                ('budgeting_from', models.DateField(blank=True, null=True)),
                ('budgeting_to', models.DateField(blank=True, null=True)),
                ('IRB_new_review', models.DateField(blank=True, null=True)),
                ('IRB_qualified_permission', models.DateField(blank=True, null=True)),
                ('IRB_finalization', models.DateField(blank=True, null=True)),
                ('contract', models.DateField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('pre_initiation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.pre_initiation')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pre_Initiation_IIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('crms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.crms')),
                ('etc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.etc')),
                ('irb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='IRB', to='research.irb')),
                ('mfds', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='MFDS', to='research.mfds')),
                ('multicenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.multicenter')),
                ('pre_initiation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.pre_initiation')),
                ('preperation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.preperation')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
