# Generated by Django 3.1.4 on 2023-07-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0042_auto_20230216_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='CRA',
            new_name='CRA_name',
        ),
        migrations.AddField(
            model_name='research',
            name='CRA_phoneNumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='sponsor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
