# Generated by Django 3.1.4 on 2023-07-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0043_auto_20230726_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='end_research',
            old_name='CRA',
            new_name='CRA_name',
        ),
        migrations.AddField(
            model_name='end_research',
            name='CRA_phoneNumber',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='end_research',
            name='sponsor',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
