# Generated by Django 3.1.4 on 2023-08-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0044_auto_20230731_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='end_research',
            name='study_coordinator',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
