# Generated by Django 3.1.4 on 2023-08-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0045_end_research_study_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='study_coordinator',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
