# Generated by Django 3.1.4 on 2023-08-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0046_research_study_coordinator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='research',
            old_name='sponsor',
            new_name='CRO',
        ),
    ]
