# Generated by Django 3.1.4 on 2023-08-03 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0047_auto_20230803_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pre_initiation',
            old_name='company',
            new_name='sponsor',
        ),
    ]
