# Generated by Django 3.1.4 on 2023-08-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0048_auto_20230803_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='cris_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='irb_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
