# Generated by Django 3.1.4 on 2023-08-18 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0049_auto_20230810_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='research',
            name='arm_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Study_SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_subcategory', to='research.study_category')),
            ],
        ),
        migrations.CreateModel(
            name='Study_Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('pre_initiation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_memo', to='research.pre_initiation')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_memo', to='research.study_subcategory')),
            ],
        ),
    ]
