# Generated by Django 3.1.4 on 2023-09-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0050_auto_20230818_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteOfAdministration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[], max_length=120, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
