# Generated by Django 3.1.4 on 2023-09-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0051_routeofadministration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RouteOfAdministration',
            new_name='Route_Of_Administration',
        ),
    ]
