# Generated by Django 3.1.4 on 2023-09-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0052_auto_20230908_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='route_of_administration',
            field=models.ManyToManyField(to='research.Route_of_Administration'),
        ),
    ]
