# Generated by Django 3.1.4 on 2023-09-12 10:42

from django.db import migrations, models
import django.db.models.deletion
import research.models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0053_research_route_of_administration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='route_of_administration',
            field=models.ManyToManyField(to='research.Route_of_Administration'),
        ),
        migrations.CreateModel(
            name='UploadReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=800)),
                ('file', models.FileField(upload_to=research.models.uploadreference_directory_path)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.research')),
            ],
        ),
        migrations.CreateModel(
            name='UploadInclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=800)),
                ('file', models.FileField(upload_to=research.models.uploadinclusion_directory_path)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.research')),
            ],
        ),
        migrations.CreateModel(
            name='UploadExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=800)),
                ('file', models.FileField(upload_to=research.models.uploadexclusion_directory_path)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.research')),
            ],
        ),
        migrations.CreateModel(
            name='UploadEngFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=800)),
                ('file', models.FileField(upload_to=research.models.uploadengfile_directory_path)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.research')),
            ],
        ),
    ]
