# Generated by Django 3.1.4 on 2023-09-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0054_auto_20230912_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='route_of_administration',
            field=models.ManyToManyField(to='research.Route_of_Administration'),
        ),
    ]
