# Generated by Django 3.1.4 on 2023-09-26 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0055_auto_20230915_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='route_of_administration',
            field=models.ManyToManyField(to='research.Route_of_Administration'),
        ),
        migrations.CreateModel(
            name='DownloadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=100)),
                ('downloader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
