# Generated by Django 3.1.4 on 2023-10-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0056_auto_20230926_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='route_of_administration',
            field=models.ManyToManyField(to='research.Route_of_Administration'),
        ),
    ]
