# Generated by Django 3.1.4 on 2023-10-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20230905_1736'),
        ('research', '0059_auto_20231011_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='CRO',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.company'),
        ),
        migrations.AlterField(
            model_name='research',
            name='route_of_administration',
            field=models.ManyToManyField(to='research.Route_of_Administration'),
        ),
    ]
