# Generated by Django 3.1.4 on 2023-10-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0060_auto_20231012_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='route_of_administration',
            field=models.ManyToManyField(to='research.Route_of_Administration'),
        ),
    ]
