# Generated by Django 3.1.4 on 2023-12-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0061_auto_20231013_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='pre_initiation',
            name='tx',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pre_initiation_sit',
            name='SIV',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='route_of_administration',
            field=models.ManyToManyField(to='research.Route_of_Administration'),
        ),
    ]
