# Generated by Django 3.1.4 on 2024-01-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0062_auto_20231227_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='route_of_administration',
            field=models.ManyToManyField(to='research.Route_of_Administration'),
        ),
    ]
