# Generated by Django 3.1.4 on 2021-07-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
