# Generated by Django 3.1.4 on 2021-09-01 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('work_phone', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, choices=[('제중관 B1층', '제중관 B1층'), ('광혜관 B1층', '광혜관 B1층 (1)'), ('광혜관 B3층 (1)', 'On 광혜관 B3층 (1)'), ('광혜관 B3층 (2)', '광혜관 B3층 (2)'), ('15A 병동 신약 모니터링실', '15A 병동 신약 모니터링실'), ('암병원 4층', '암병원 4층'), ('제중관 2층', '제중관 2층')], max_length=50)),
                ('onco_A', models.BooleanField(default=False)),
                ('name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
