# Generated by Django 3.1.4 on 2021-09-01 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210901_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, choices=[('제중관 B1층', '제중관 B1층'), ('광혜관 B1층', '광혜관 B1층 (1)'), ('광혜관 B3층 (1)', '광혜관 B3층 (1)'), ('광혜관 B3층 (2)', '광혜관 B3층 (2)'), ('15A 병동 신약 모니터링실', '15A 병동 신약 모니터링실'), ('암병원 4층', '암병원 4층'), ('제중관 2층', '제중관 2층')], max_length=50),
        ),
    ]
