# Generated by Django 3.1.4 on 2021-12-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210909_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='career',
            field=models.DateField(blank=True, null=True),
        ),
    ]
