# Generated by Django 3.1.4 on 2022-01-03 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_contact_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='team',
            field=models.CharField(blank=True, choices=[('CLUE', 'CLUE'), ('GSI', 'GSI'), ('etc', 'etc')], max_length=50, null=True),
        ),
    ]
