# Generated by Django 3.1.4 on 2022-01-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_contact_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='eng_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
