# Generated by Django 3.1.4 on 2023-02-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='eng_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
