# Generated by Django 3.1.4 on 2024-07-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20230821_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_senior',
            field=models.BooleanField(default=False),
        ),
    ]
